### ISSUE TITLE
error Can't connect to local MySQL server through socket when create zabbix 

### ISSUE THREAD

**Issue by fearlee** [a13m/openshift-zabbix-cartridge#5]
can you help me ? i use rhc to create new zabbix apps, but i get this kind of error 

rhc create-app mynewcart http://zabbix-agrimm.rhcloud.com/build/manifest/956c50b33467659120c5ad7ecc9d134c6fe1a214

Creating application 'mynewcart' ...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket
'/var/lib/mysql/mysql.sock' (2)
ERROR 2002 (HY000): Can't connect to local MySQL server through socket
'/var/lib/mysql/mysql.sock' (2)
ERROR 2002 (HY000): Can't connect to local MySQL server through socket
'/var/lib/mysql/mysql.sock' (2)
ERROR 2002 (HY000): Can't connect to local MySQL server through socket
'/var/lib/mysql/mysql.sock' (2)
/var/lib/openshift/538b377376b77eaa4a000098/zabbix//sbin/zabbix_server: error while loading
shared libraries: libmysqlclient.so.16: cannot open shared object file: No such file or
directory
WARNING:  Unable to pull data from 'https://rubygems.org/': no such name
(https://rubygems.org/specs.4.8.gz)
Traceback (most recent call last):
  File "/var/lib/openshift/538b377376b77eaa4a000098/zabbix//usr/bin/zabbix-import-template",
line 97, in <module>
    zbx.zbxAuth()
  File "/var/lib/openshift/538b377376b77eaa4a000098/zabbix//usr/bin/zabbix-import-template",
line 32, in zbxAuth
    res = self.printResult(login)
  File "/var/lib/openshift/538b377376b77eaa4a000098/zabbix//usr/bin/zabbix-import-template",
line 93, in printResult
    return json.load(response)
  File "/usr/lib64/python2.7/json/**init**.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by LudoMeurillon** [comment]
Are you using Openshift Enterprise with a custom EXTERNAL_ETH_DEV configuration on broker ?

I ran into a similar error when using current zabbix server cartrige with this configuration (see https://github.com/a13m/openshift-zabbix-cartridge/issues/3)

**Comment by fearlee** [comment]
i try to install it at openshift origin v3.
two machine, one broker one node. fedora 19

i use eth0 as my main eth

**Comment by LudoMeurillon** [comment]
Did you try with mysql cartridge on your app adding "mysql-5.1" or "mysql-5.5" on your command-line ?

Example : 

``` bash
rhc create-app mynewcart http://zabbix-agrimm.rhcloud.com/build/manifest/956c50b33467659120c5ad7ecc9d134c6fe1a214 mysql-5.1
```
